

export const fetchTypes = {
    "REQUEST": "FETCH_SOURCE_REQUEST",
    "SUCCESS": "FETCH_SOURCE_SUCCESS",
    "FAILURE": "FETCH_SOURCE_FAILURE",
}


export const fetchAllTypes = {
    "REQUEST": "FETCHALL_SOURCE_REQUEST",
    "SUCCESS": "FETCHALL_SOURCE_SUCCESS",
    "FAILURE": "FETCHALL_SOURCE_FAILURE",
}

export const syncTypes = {
    "ADD_SOURCE": "ADD_SOURCE",
    "REMOVE_SOURCE": "REMOVE_SOURCE",
    "UPDATE_SOURCE": "UPDATE_SOURCE",
    "ADD_HIGHLIGHT": "ADD_HIGHLIGHT",
    "REMOVE_HIGHLIGHT": "REMOVE_HIGHLIGHT",
    "UPDATE_HIGHLIGHT": "UPDATE_HIGHLIGHT",
}
